platform :ios, '17.5'

target 'App' do
  # Pods for App
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunitySqlite', :path => '../../node_modules/@capacitor-community/sqlite'
  # Add other pods here
end
